### ISSUE TITLE
slow 

### ISSUE THREAD

**Issue by qlinsey** [johnrobinsn/diffusion_experiments#1]
Hi, may i ask:
I am running this from google colab: ([diffusion_experiments](https://github.com/johnrobinsn/diffusion_experiments)/DiffEdit.ipynb)

 mask = calc_diffedit_diff(latent,'Bowl of Strawberries','Bowl of Oranges',seed=seed).

It is very slow. I am using google colab free account, how long will it take to generate a mask (exactly same this google colab example)? I have waited for more than 30 minutes, still running. 

Thank you!

**Comment by qlinsey** [comment]
2 hours still running

**Comment by johnrobinsn** [comment]
Did you change the runtime to GPU?  takes about ~ 5 minutes with GPU enabled.  just tried it again.

Note the warning at the top of the notebook.  

If you have GPU enabled then I'm not sure... just tried it again myself... and took about 5 minutes.

**Comment by qlinsey** [comment]
Hi, John 

Thanks. Yes, I am using GPU from google colab free account. It kept loading and never generated any output after a few hours. 

Linsey 
     On Monday, 13 March 2023, 03:24:28 pm GMT-7, John Robinson ***@***.***> wrote:  
 
 


Did you change the runtime to GPU? takes about ~ 5 minutes with GPU enabled. just tried it again.

Note the warning at the top of the notebook.

If you have GPU enabled then I'm not sure... just tried it again myself... and took about 5 minutes.

**Comment by qlinsey** [comment]
Hi, John, thanks, it works.
